function S = BZPatternGenerator(T0, T1, dT, InitialStep, par, IC, Nsim, devices)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

N = sqrt(size(IC,1) / 2);

if N ~= 32 && N ~= 64
    error('The resolution of spatial grid has to be equal to 32 or 64!');
end

cudaMexExists = false;
if N == 32 && exist('BZPatternGeneratorX32')
    cudaMexExists = true;
end
if N == 64 && exist('BZPatternGeneratorX64')
    cudaMexExists = true;
end

if cudaMexExists
    if N == 32
        S = BZPatternGeneratorX32(...
            T0,...
            T1,...
            dT,...
            InitialStep,...
            par,... 
            IC,... 
            Nsim,...
            devices);
    else
        S = BZPatternGeneratorX64(...
            T0,...
            T1,...
            dT,...
            InitialStep,...
            par,... 
            IC,... 
            Nsim,...
            devices);
    end
elseif exist('BZPatternGeneratorCPP')
    S = BZPatternGeneratorCPP(...
        T0,...
        T1,...
        N,...
        InitialStep,...
        par,...
        IC,...
        Nsim);
else
    f = @(U,V,p) (p.A - (p.B+1)*U + U.^2.*V);
    g = @(U,V,p) (p.B*U - U.^2.*V);
    S = RDPatternGenerator(f,g,T0,T1,par,IC,Nsim,N);
end

end

