function S = FHNPatternGenerator(T0, T1, dT, InitialStep, par, IC, Nsim, devices)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

N = sqrt(size(IC,1) / 2);

if N ~= 32 && N ~= 64
    error('The resolution of spatial grid has to be equal to 32 or 64!');
end

cudaMexExists = false;
if N == 32 && exist('FHNPatternGeneratorX32')
    cudaMexExists = true;
end
if N == 64 && exist('FHNPatternGeneratorX64')
    cudaMexExists = true;
end

if cudaMexExists
    if N == 32
        S = FHNPatternGeneratorX32(...
            T0,...
            T1,...
            dT,...
            InitialStep,...
            par,... 
            IC,... 
            Nsim,...
            devices);
    else
        S = FHNPatternGeneratorX64(...
            T0,...
            T1,...
            dT,...
            InitialStep,...
            par,... 
            IC,... 
            Nsim,...
            devices);
    end
elseif exist('FHNPatternGeneratorCPP')
    S = FHNPatternGeneratorCPP(...
        T0,...
        T1,...
        N,...
        InitialStep,...
        par,...
        IC,...
        Nsim);
else
    f = @(U,V,p) p.eps*(V - p.B*U - p.A);
    g = @(U,V,p) -U + p.mu*V - V.^3;
    S = RDPatternGenerator(f,g,T0,T1,par,IC,Nsim,N);
end

end

